# Huegelfest Docker Compose Konfiguration

services:
  huegelfest-app:
    image: xilefma/huegelfest-web:latest
    env_file:
      - .env.production
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: huegelfest
    ports:
      - "9049:3000"
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - huegelfest-network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: huegelfest
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - huegelfest-network

volumes:
  mongodb_data:

networks:
  huegelfest-network:
    driver: bridge 