version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "9049:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://huegeluser:huegeluser123@mongodb:27017/huegelfest?authSource=huegelfest&authMechanism=SCRAM-SHA-256
      - JWT_SECRET=m0ZAvEBqbYUajAl8432FvN7fRqqhpewh02z1K5m0BWw=
      - NEXT_PUBLIC_SITE_URL=https://huegelfest.fansel.dev
      - NEXT_PUBLIC_VAPID_PUBLIC_KEY=BGaY-2eeg8pi2yNRIsLdm4SN4RmHTKdVwaeEdZeUpJSMv9isl12K0TadiH9GDDWo96r7OFFMPdurXoSEiu0nnH4
      - VAPID_PRIVATE_KEY=19N-DzH4SjTHGvhapCSm3o61V0iGaqJu6zGWvJ5zrsI
      - NEXT_PUBLIC_ADMIN_PASSWORD=$2b$10$qQTtbrROj30/QeF5qh14wesvA8JSbJgs0OcE0q8E4t7RVMgUfeLry
      - SOUNDCLOUD_CLIENT_ID=JtwkMxXKQNqDFvsQ3pUayFVgt4j9dS87
      - ADMIN_USERNAME=felix
      - ADMIN_PASSWORD=supergeil
    volumes:
      - ./database:/app/database:ro
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - huegelfest-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      sh -c "node /app/database/init-db.js && npm start"

  mongodb:
    image: mongo:latest
    command: ["--auth"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=huegeladmin
      - MONGO_INITDB_ROOT_PASSWORD=huegeladmin123
      - MONGO_INITDB_DATABASE=huegelfest
      - MONGO_INITDB_USERNAME=huegeluser
      - MONGO_INITDB_PASSWORD=huegeluser123
    volumes:
      - mongodb_data:/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - huegelfest-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  huegelfest-network:
    driver: bridge 