FROM node:20-alpine AS builder

WORKDIR /app

# Kopiere nur package.json und package-lock.json
COPY package*.json ./

# Installiere Dependencies mit Cache
RUN npm ci

# Produktions-Image
FROM node:20-alpine

WORKDIR /app

# Kopiere nur die notwendigen Dateien aus dem Builder
COPY --from=builder /app/node_modules ./node_modules
COPY package*.json ./

# Setze Berechtigungen
RUN chown -R node:node /app

# Wechsle zu non-root User
USER node 