# Huegelfest Docker Compose Konfiguration
version: '3.8'

services:
  huegelfest-app:
    image: xilefma/huegelfest-web:latest
    env_file:
      - .env.production
    ports:
      - "9049:3000"
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - huegelfest-network

  mongodb:
    image: mongo:latest
    command: ["--auth"]
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    restart: unless-stopped
    networks:
      - huegelfest-network

volumes:
  mongodb_data:

networks:
  huegelfest-network:
    driver: bridge 