FROM node:18-alpine

WORKDIR /app

# Installiere Abhängigkeiten
COPY package.json package-lock.json ./
RUN npm ci

# Kopiere den Rest des Codes
COPY . .

# Setze Umgebungsvariablen
ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1

# Exponiere den Port
EXPOSE 3000

# Starte die Anwendung im Entwicklungsmodus
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"] 