#!/bin/bash

# Deployment-Verzeichnis
DEPLOY_DIR="/opt/huegelfest"
REPO_DIR="$DEPLOY_DIR/repo"
APP_DIR="$DEPLOY_DIR/app"

# Git-Repository aktualisieren
cd $REPO_DIR
git --work-tree=$APP_DIR --git-dir=$REPO_DIR/.git checkout -f

# Berechtigungen setzen
chmod -R 755 $APP_DIR
chown -R fansel:fansel $APP_DIR

# Container neu starten
cd $APP_DIR
docker compose down
docker builder prune -f
docker compose up -d --build 