#!/bin/bash
set -e

# Pfade
BASE_DIR="/opt/huegelfest"
APP_DIR="$BASE_DIR/app"
REPO_DIR="$BASE_DIR/repo"

# Altes App-Verzeichnis löschen und neu klonen
rm -rf $APP_DIR
git clone $REPO_DIR $APP_DIR

# Docker Compose neu starten
cd $APP_DIR
docker-compose down
docker-compose up -d --build 