export type View =
  | 'home'
  | 'anreise'
  | 'carpool'
  | 'activities'
  | 'infoboard'
  | 'settings'
  | 'admin'
  | 'favorites'
  | 'announcements'
  | 'workingGroups'
  | 'timeline'
  | 'admin-settings'
  | 'signup'
  | 'packlist'
  | 'concepts'; 