name: Docker Build and Push

on:
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push web app
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          cache-from: type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/huegelfest-web:buildcache,ignore-error=true
          cache-to: type=registry,ref=${{ env.DOCKERHUB_USERNAME }}/huegelfest-web:buildcache,mode=max
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/huegelfest-web:latest
            ${{ env.DOCKERHUB_USERNAME }}/huegelfest-web:${{ github.sha }}